<%@ Page Language="C#" AutoEventWireup="true" CodeFile="EditUsers.aspx.cs" Inherits="MonthSummary" ValidateRequest="False" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
	<link rel="stylesheet" type="text/css" href="TR.css" />	
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <table style="width:100%;">
		 <tr>
			 <td>
					 <asp:Panel ID="Panel2" runat="server" Height="25px" 
						 HorizontalAlign="Center" CssClass="textpanel">
						 <asp:Label ID="Label2" runat="server" 
	Text="Configure Users" Font-Names="Arial" Font-Size="Large"></asp:Label>
					 </asp:Panel>
				 </td>
		 </tr>
		 <tr>
			 <td>
				 <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
					 ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
					 DeleteCommand="DELETE FROM [PERSONS] WHERE [PERSON_ID] = ?" 
					 InsertCommand="INSERT INTO [PERSONS] ([PERSON_ID], [PERSON_NAME], [IN_WORK], [ADDRESS], [USER_PASSWORD], [IS_ADMIN], [PERSON_LOGIN], [PERSON_PHONE], [PERSON_CELL_PHONE], [PERSON_COLOR], [PERSON_BIRTHDAY], [PERSON_NO], [WORK_EMAIL]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)" 
					 OldValuesParameterFormatString="original_{0}" 
					 ProviderName="System.Data.OleDb" 
					 SelectCommand="SELECT [PERSON_ID], [PERSON_NAME], [IN_WORK], [ADDRESS], [USER_PASSWORD], [IS_ADMIN], [PERSON_LOGIN], [PERSON_PHONE], [PERSON_CELL_PHONE], [PERSON_COLOR], [PERSON_BIRTHDAY], [PERSON_NO], [WORK_EMAIL] FROM [PERSONS]" 
					 
					 
					 
					 UpdateCommand="UPDATE [PERSONS] SET [PERSON_NAME] = ?, [IN_WORK] = ?, [ADDRESS] = ?, [USER_PASSWORD] = ?, [IS_ADMIN] = ?, [PERSON_LOGIN] = ?, [PERSON_PHONE] = ?, [PERSON_CELL_PHONE] = ?, [PERSON_COLOR] = ?, [PERSON_BIRTHDAY] = ?, [PERSON_NO] = ?, [WORK_EMAIL] = ? WHERE [PERSON_ID] = ?">
					 <DeleteParameters>
						 <asp:Parameter Name="original_PERSON_ID" Type="Int32" />
					 </DeleteParameters>
					 <UpdateParameters>
						 <asp:Parameter Name="PERSON_NAME" Type="String" />
						 <asp:Parameter Name="IN_WORK" Type="Boolean" />
						 <asp:Parameter Name="ADDRESS" Type="String" />
						 <asp:Parameter Name="USER_PASSWORD" Type="String" />
						 <asp:Parameter Name="IS_ADMIN" Type="Boolean" />
						 <asp:Parameter Name="PERSON_LOGIN" Type="String" />
						 <asp:Parameter Name="PERSON_PHONE" Type="String" />
						 <asp:Parameter Name="PERSON_CELL_PHONE" Type="String" />
						 <asp:Parameter Name="PERSON_COLOR" Type="Int32" />
						 <asp:Parameter Name="PERSON_BIRTHDAY" Type="DateTime" />
						 <asp:Parameter Name="PERSON_NO" Type="String" />
						 <asp:Parameter Name="WORK_EMAIL" Type="String" />
						 <asp:Parameter Name="original_PERSON_ID" Type="Int32" />
					 </UpdateParameters>
					 <InsertParameters>
						 <asp:Parameter Name="PERSON_ID" Type="Int32" />
						 <asp:Parameter Name="PERSON_NAME" Type="String" />
						 <asp:Parameter Name="IN_WORK" Type="Boolean" />
						 <asp:Parameter Name="ADDRESS" Type="String" />
						 <asp:Parameter Name="USER_PASSWORD" Type="String" />
						 <asp:Parameter Name="IS_ADMIN" Type="Boolean" />
						 <asp:Parameter Name="PERSON_LOGIN" Type="String" />
						 <asp:Parameter Name="PERSON_PHONE" Type="String" />
						 <asp:Parameter Name="PERSON_CELL_PHONE" Type="String" />
						 <asp:Parameter Name="PERSON_COLOR" Type="Int32" />
						 <asp:Parameter Name="PERSON_BIRTHDAY" Type="DateTime" />
						 <asp:Parameter Name="PERSON_NO" Type="String" />
						 <asp:Parameter Name="WORK_EMAIL" Type="String" />
					 </InsertParameters>
				 </asp:SqlDataSource>
				 <asp:GridView ID="GridView1" runat="server" AllowSorting="True" 
					 AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
					 AutoGenerateEditButton="True" BackColor="#3399FF" BorderColor="Tan" 
					 BorderWidth="1px" CellPadding="2" DataSourceID="SqlDataSource1" 
					 Font-Names="arial" Font-Size="Smaller" ForeColor="Black" 
					 HorizontalAlign="Center" DataKeyNames="PERSON_ID" 
					 onrowdatabound="GridView_RowDataBound" onrowupdated="GridView1_RowUpdated" 
					 onrowupdating="GridView1_RowUpdating">
					 <RowStyle BorderStyle="None" CssClass="smalltext" />
					 <Columns>
						 <asp:BoundField DataField="PERSON_ID" HeaderText="ID" InsertVisible="False" 
							 ReadOnly="True" SortExpression="PERSON_ID" />
						 <asp:BoundField DataField="PERSON_NAME" HeaderText="PERSON_NAME" 
							 SortExpression="PERSON_NAME" />
						 <asp:CheckBoxField DataField="IN_WORK" HeaderText="WORK" 
							 SortExpression="IN_WORK">
						 <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
						 </asp:CheckBoxField>
						 <asp:BoundField DataField="ADDRESS" HeaderText="ADDRESS" 
							 SortExpression="ADDRESS">
						 <ItemStyle Wrap="False" />
						 </asp:BoundField>
						 <asp:BoundField DataField="PERSON_LOGIN" HeaderText="LOGIN" 
							 SortExpression="PERSON_LOGIN" />
						 <asp:BoundField DataField="USER_PASSWORD" HeaderText="PASS" 
							 SortExpression="USER_PASSWORD" />
						 <asp:CheckBoxField DataField="IS_ADMIN" HeaderText="ADMIN" 
							 SortExpression="IS_ADMIN">
						 <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
						 </asp:CheckBoxField>
						 <asp:BoundField DataField="PERSON_PHONE" HeaderText="PHONE" 
							 SortExpression="PERSON_PHONE">
						 <ItemStyle Wrap="False" />
						 </asp:BoundField>
						 <asp:BoundField DataField="PERSON_CELL_PHONE" HeaderText="MOBILE" 
							 SortExpression="PERSON_CELL_PHONE">
						 <ItemStyle Wrap="False" />
						 </asp:BoundField>
						 <asp:BoundField DataField="PERSON_COLOR" HeaderText="COLOR" 
							 SortExpression="PERSON_COLOR" />
						 <asp:BoundField DataField="PERSON_BIRTHDAY" DataFormatString="{0:dd:MM:yyyy}" 
							 HeaderText="BIRTHDAY" SortExpression="PERSON_BIRTHDAY" />
						 <asp:BoundField DataField="PERSON_NO" HeaderText="PASSPORT" 
							 SortExpression="PERSON_NO" />
						 <asp:BoundField DataField="WORK_EMAIL" HeaderText="EMAIL" 
							 SortExpression="WORK_EMAIL" />
					 </Columns>
					 <FooterStyle BackColor="Tan" CssClass="smalltext" />
					 <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" 
						 HorizontalAlign="Center" />
					 <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
					 <HeaderStyle BackColor="#9999FF" Font-Bold="True" CssClass="smalltext" />
					 <EditRowStyle CssClass="smalltext" />
					 <AlternatingRowStyle BackColor="PaleGoldenrod" />
				 </asp:GridView>
			 </td>
		 </tr>
		 <tr>
			 <td>
    <hr />
	 <asp:Panel ID="Panel3" runat="server" CssClass="textpanel">
		 <asp:Label ID="Intro" runat="server" 
		 Text="Office work report."></asp:Label>
	 </asp:Panel>
    		</td>
		 </tr>
	 </table>
    </form>
</body>
</html>
