using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using GTOHELPER;

public partial class MonthSummary : GTOHelper
{
	protected void Page_Load(object sender, EventArgs e)
	{
		GridView1.AutoGenerateDeleteButton = IsAdmin;
		GridView1.AutoGenerateEditButton = IsAdmin;
		SqlDataSource1.ConnectionString = ConnString;
		if (UserID == -1)
			return;
	}
	protected void GridView_RowDataBound(object sender, GridViewRowEventArgs e)
	{
		if (e.Row.RowType == DataControlRowType.DataRow)
		{
			if (!IsAdmin)
			{
				e.Row.Cells[5].Text = "*****";
			}
			HyperLink hr = new HyperLink();
			hr.Text = e.Row.Cells[2].Text;
			hr.NavigateUrl = "DailySearch.aspx?name=" + e.Row.Cells[2].Text;
			e.Row.Cells[2].Controls.Add(hr);
		}
	}
	protected void GridView1_RowUpdated(object sender, GridViewUpdatedEventArgs e)
	{

	}
	protected void GridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
	{

	}
}
