using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using GTOHELPER;
using System.Net.NetworkInformation;
using System.Net;
using System.Data;
using System.Text;

public partial class PCHandle : GTOHelper
{
	protected void Page_Load(object sender, EventArgs e)
	{
		GridView1.AutoGenerateDeleteButton = IsAdmin;
		GridView1.AutoGenerateEditButton = IsAdmin;
		SqlDataSource1.ConnectionString = ConnString;
		GridView1.DataBind();
	}
	protected void ScanButton_Click(object sender, EventArgs e)
	{
		for (int i = 1; i < 256; i++)
		{
			string strIP = "192.168.0." + i.ToString();
			try
			{
					string strHost = Dns.GetHostByAddress(strIP).HostName.ToUpper();
// 				string strHost = Dns.GetHostEntry(strIP).HostName.ToUpper();
				DataSet ds = GetDataSet("SELECT ID, PCNAME, IP FROM PCS WHERE PCNAME = '" + strHost + "' OR IP = '" + strIP + "'");
				bool bUpdated = false;
				foreach (DataRow rowCur in ds.Tables[0].Rows)
				{
					//removing duplicates in ip / name
					if (!bUpdated)
					{
						SQLExecute("UPDATE PCS SET PCNAME = '" + strHost + "', IP = '" + strIP + "' WHERE ID = " + rowCur[0].ToString());
						bUpdated = true;
					}
					else
						SQLExecute("DELETE FROM PCS WHERE ID = " + rowCur[0].ToString());
				}

				if (!bUpdated)
					SQLExecute("INSERT INTO PCS (PCNAME, IP) VALUES ('" + strHost + "', '" + strIP + "')");

				Application.Lock();
				Application[strIP] = true.ToString();
				Application.UnLock();
			}
			catch (System.Exception /*ex*/)
			{
				Application.Lock();
				Application[strIP] = false.ToString();
				Application.UnLock();
			}
		}
	}
	protected void GridView1_RowDataBound(object sender, GridViewRowEventArgs e)
	{
		if (e.Row.RowType == DataControlRowType.DataRow)
		{
			//e.Row.Cells[].Text = (e.Row.DataItemIndex + 1).ToString();
		}
	}
	protected void CheckButton_Click(object sender, EventArgs e)
	{

	}

// IPInfo
// snmpmgr1.Timeout = 10;
// snmpmgr1.RemoteHost = "10.0.1.11";
// 	    
// snmpmgr1.ObjCount = 1;
// snmpmgr1.ObjId[1] = "1.3.6.1.2.1.2.1"; //ifEntryNum snmpmgr1.SendGetNextRequest();
// int ifindex = Convert.ToInt32(snmpmgr1.ObjValue[1]);
// textBox1.AppendText("Number of interfaces: " + snmpmgr1.ObjValue[1] + "\r\n");
// 
// snmpmgr1.ObjCount = 2;
// snmpmgr1.ObjId[1] = "1.3.6.1.2.1.2.2.1.3"; 
// //ifEntryType, this is "6" for an ethernet adapter, "24" for loopback interface 
// //For a full list see rfc 1573
// snmpmgr1.ObjId[2] = "1.3.6.1.2.1.2.2.1.6"; //ifPhysAddress 
// for (int i = 1; i<= ifindex; i++)
// {
//   snmpmgr1.SendGetNextRequest();
//   textBox1.AppendText(i.ToString() + ".  Type " + snmpmgr1.ObjValue[1]);
//   string hexval = "";
//   for (int j = 0; j< snmpmgr1.ObjValueB[2].Length; j++)
//   {
//     hexval = hexval + snmpmgr1.ObjValueB[2][j].ToString("X") + " ";
//   }
//   textBox1.AppendText(", MAC address: " + hexval + "\r\n");
// }
	public static string GetMAC(string strPC)
	{
// 		 ConnectionOptions options = new ConnectionOptions();
// 		 options.Username = "mps\admin";
// 		 options.Password = "alis_mps_911";
// 		 options.SecurePassword = "alis_mps_911";
// 
// 		 ManagementScope theScope = new ManagementScope("\\\\" + strPC + "\\root\\cimv2", options);
// 
// 		 StringBuilder theQueryBuilder = new StringBuilder();
// 		 theQueryBuilder.Append("SELECT MACAddress FROM Win32_NetworkAdapter");
// 		 ObjectQuery theQuery = new ObjectQuery(theQueryBuilder.ToString());
// 		 ManagementObjectSearcher theSearcher = new ManagementObjectSearcher(theScope, theQuery);
// 		 ManagementObjectCollection theCollectionOfResults = theSearcher.Get();
// 
// 		 foreach (ManagementObject theCurrentObject in theCollectionOfResults)
// 		 {
// 			 return theCurrentObject["MACAddress"].ToString();
// 		 }
// 		 return "";
		string strCommand = "getmac /U mps\admin /P alis_mps911 /s " + strPC;
		System.Diagnostics.ProcessStartInfo procStartInfo = new System.Diagnostics.ProcessStartInfo("cmd", "/c " + strCommand);
		procStartInfo.RedirectStandardOutput = true;
		procStartInfo.UseShellExecute = false;
		procStartInfo.CreateNoWindow = true;
		System.Diagnostics.Process proc = new System.Diagnostics.Process();
		proc.StartInfo = procStartInfo;
		proc.Start();
		proc.WaitForExit();
		return proc.StandardOutput.ReadToEnd();
	}
	protected void CheckButton1_Click(object sender, EventArgs e)
	{
		DataSet ds = GetDataSet("SELECT ID, PCNAME FROM PCS");
		int i = 0;
		foreach (DataRow rowCur in ds.Tables[0].Rows)
		{
			i++;
			if (i == 1)
				continue;

			string str1 = GetMAC(rowCur[1].ToString());
// 			string strCommand = "getmac /U mps\admin /P alis_mps911 /s " + rowCur[1].ToString();
// 			System.Diagnostics.ProcessStartInfo procStartInfo = new System.Diagnostics.ProcessStartInfo("cmd", "/c " + strCommand);
// 			procStartInfo.RedirectStandardOutput = true;
// 			procStartInfo.UseShellExecute = false;
// 			procStartInfo.CreateNoWindow = true;
// 			System.Diagnostics.Process proc = new System.Diagnostics.Process();
// 			proc.StartInfo = procStartInfo;
// 			proc.Start();
// 			proc.WaitForExit();
// 			string result = proc.StandardOutput.ReadToEnd();
// 			proc.WaitForExit();			
		}
	}
}
